spring.config.import=optional:file:../.env.spring[.properties]

# Logging
logging.level.org.springframework.context=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.root=INFO
logging.level.org.springframework.cache=TRACE

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

# Project configuration
keycloak.url=http://localhost:8080/auth
keycloak.public-url=https://localhost/auth